### ISSUE TITLE
Contact List is empty in android, but works fine in IOS

### ISSUE THREAD

**Issue by pavithrac16** [AppLozic/Applozic-React-Native-Chat-Messaging-SDK#11]
I have integrated the react native chat SDK on ios and android.

Created few users and it shows up in ios but in android Contact list is empty. 

Can you guide me where i'm going wrong.. i dont see any errors or logs.

**Comment by Sunilkumarr** [comment]
You need to add the applozic-settings.json file from this  [link](https://docs.applozic.com/docs/android-chat-theme-and-customization#section-applozic-customization-json-settings)  and make   "registeredUserContactListCall": true,
