### ISSUE TITLE
Firebase Push Notification support

### ISSUE THREAD

**Issue by murtraja** [AppLozic/Applozic-React-Native-Chat-Messaging-SDK#14]
Hello,

The [documentation](https://docs.applozic.com/docs/react-native-push-notification) for implementing receipt of push notifications for Applozic completely takes the native approach without providing any Javascript methods.

This creates a problem wherein we already are using react-native-firebase for all our firebase related implementations including MessageListeners, which provides a convenient platform independent way of handling notifications.

Therefore, we do not have a way of following the steps mentioned in the doc for setting up firebase notifications via a custom service. I tried to implement something [here](https://github.com/murtraja/Applozic-React-Native-Chat-Messaging-SDK/blob/master/android/src/main/java/com/applozic/ApplozicChatModule.java) which does the job for Android, but I needed some help with

1. If it is the right way to go?
2. Are you planning to implement it in the near future?
3. Can you help us with iOS implementation for the same?

**Comment by Sunilkumarr** [comment]
@murtraja Thanks for PR suggestion. We are currntly evaluating changes if it looks fine will add support for IOS as well.

**Comment by reytum** [comment]
@murtraja The changes are not required as you can directly update the firebase plugin files with applozic code for notifications to work with android and ignore the setup mentioned in the docs. For iOS you will have to follow the steps mentioned in applozic doc as we are using APNS and thus this firebase notification won't work for iOS.

Follow the below steps for notifications to work in android along with the firebase plugin:
```
1) Open node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessagingService.java file and do the below changes:
a) search for the line : Log.d(TAG, "onMessageReceived event received");
and just below it add the below code:

if (message.getData().size() >0) {
if (MobiComPushReceiver.isMobiComPushNotification(remoteMessage.getData())) {
Log.i(TAG, "Applozic notification processing...");
MobiComPushReceiver.processMessageAsync(this, remoteMessage.getData());
return;
}
}

b) search for the line : Log.d(TAG, "onNewToken event received");
and below it add the below code:

Applozic.getInstance(this).setDeviceRegistrationId(registrationId);
if (MobiComUserPreference.getInstance(this).isRegistered()) {
try {
RegistrationResponse registrationResponse = new RegisterUserClientService(this).updatePushNotificationId(registrationId);
} catch (Exception e) {
e.printStackTrace();
}
}

c) Add the below imports below the existing imports in the same file:
import com.applozic.mobicomkit.Applozic;
import com.applozic.mobicomkit.api.account.register.RegisterUserClientService;
import com.applozic.mobicomkit.api.account.register.RegistrationResponse;
import com.applozic.mobicomkit.api.account.user.MobiComUserPreference;
import com.applozic.mobicomkit.api.notification.MobiComPushReceiver;

2) Remove the below services from your AndroidManifest.xml file(if added) or the same services from applozic SDK:

<service android:name="<CLASS_PACKAGE>.FcmListenerService"
         android:stopWithTask="false">
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
</service>

<service android:name="<CLASS_PACKAGE>.FcmInstanceIDListenerService" 
         android:exported="false">
        <intent-filter>
            <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
       </intent-filter>
</service>
```

**Comment by PoojaGC** [comment]
Hello Bilal,

Can you try the sample from this repo and let us know if it works for you: https://github.com/murtraja/applozic-react-native-sample-working?
