### ISSUE TITLE
Context based Chat support

### ISSUE THREAD

**Issue by murtraja** [AppLozic/Applozic-React-Native-Chat-Messaging-SDK#15]
Hello, 

I went through the docs [here](https://docs.applozic.com/docs/android-1-1-user-chat-and-group-chat#section-context-based-chat) and noticed that the context based chat section is missing for React Native, although it present for both, Android and iOS

I wanted to know
1. If you are planning to implement this feature for react native
2. if not, what steps will be required for us to implement this from our end?

Thanks,

**Comment by reytum** [comment]
Hello @murtraja,
This is currently not exposed in react-native. If you want this , you can modify the applozic-react-native-chat under node_modules by adding the functions on both the platform from the docs. You can refer to the existing functions that are exposed.
