### ISSUE TITLE
Can't find variable NativeModules

### ISSUE THREAD

**Issue by kingtross88** [AppLozic/Applozic-React-Native-Chat-Messaging-SDK#4]
Has anyone received this error after installing the package. I've defined the variable and i keep getting this error message. 
![screen shot 2018-02-16 at 3 06 01 pm](https://user-images.githubusercontent.com/6825383/36343228-76d38d62-13d7-11e8-8520-b6956b1e6d35.png)

var ApplozicChat = NativeModules.ApplozicChat;

**Comment by kingtross88** [comment]
I'm building out in ios right now.

**Comment by adarshmishra** [comment]
Can you please check if you have added the files present [here](https://github.com/AppLozic/Applozic-React-Native-Chat-Messaging-SDK/tree/master/ios/applozic) (not only folder) in your project?

**Comment by kingtross88** [comment]
Yes I placed these files in the ios folder of my project.

I keep getting Native Module error

**Comment by kingtross88** [comment]
issue resolved. I didn't add Native Modules import

**Comment by mobileappdeveloper2019** [comment]
hello I am getting the same error in Android. so can any help help me in this matter I have follow all steps of implementing Applogic in Android.

Please let me know.

**Comment by kingtross88** [comment]
I left the platform for the lack of help and the documentation doesn't seem
to help.

**Comment by reytum** [comment]
@mobileappdeveloper2019 Have you imported the NativeModules ? Make sure you have added NativeModules in your imports.
