### ISSUE TITLE
On backpress, reloading entire app

### ISSUE THREAD

**Issue by manjunathgk22** [AppLozic/Applozic-React-Native-Chat-Messaging-SDK#44]
Hi, 
On back press, Applozic is reloading the entire app. I have attached video for reference.

 Environment
-   react-native version: 0.59.9

https://user-images.githubusercontent.com/16625464/113605808-c8853080-9664-11eb-9794-4a2601fd542a.mp4

Also how to integrate it with  [createBottomTabNavigator](https://reactnavigation.org/docs/3.x/bottom-tab-navigator) of ```react-navigation```

When I try to add it using below code 
```screen: ()=> ApplozicChat.openChat()```
App crashes because no component is returned from ``ApplozicChat.openChat()``` 
What is the workaround for this? 
Have attached the video for reference.

https://user-images.githubusercontent.com/16625464/113608444-397a1780-9668-11eb-8575-4f536efdaf7a.mp4

**Comment by Sunilkumarr** [comment]
@manjunathgk22 Hi,

On back press, Applozic is reloading the entire app. I have attached video for reference.

--> Can you share the applozic plugin version that you're using? 
  And also your android manifest file  to support@applozic.com 


When I try to add it using below code
screen: ()=> ApplozicChat.openChat()
App crashes because no component is returned from ``ApplozicChat.openChat()```
What is the workaround for this?
--> Crash seems from your app .
The function `ApplozicChat.openChat()` will just start the chat screen independently there is no concept of the component as this is a native android screen. 

Either you should move the chat option to some other place or add a dummy component and launch the chat.

**Comment by manjunathgk22** [comment]
On back press, Applozic is reloading the entire app.
This is fixed now, I have made changes in ```AndroidManifest.xml```
removed 
```android:parentActivityName=".MainActivity"```
and 
```<meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".MainActivity" />

**Comment by Sunilkumarr** [comment]
@manjunathgk22 This should not be removed you will need to add this back .

``android:parentActivityName=".MainActivity"``
and

                android:name="android.support.PARENT_ACTIVITY"
                android:value=".MainActivity" />
                
 
  For `MainActivity` you can check the       launchMode is    singleTask if its any other mode then you need to change it to singleTask
  
     android:launchMode="singleTask"
     
 and also the Applozic react native plugin needs to be latest version 1.5.1
