### ISSUE TITLE
'Applozic/Applozic-Swift.h' file not found

### ISSUE THREAD

**Issue by elainedizon** [AppLozic/Applozic-React-Native-Chat-Messaging-SDK#6]
Hi Everyone! I am not a swift expert, I followed the applozic react native tutorial on how to include it in my project but I am getting this error. Much help will be appreaciated. Thanks! If I am lacking more infor please let me know

'Applozic/Applozic-Swift.h' file not found

**Comment by murtraja** [comment]
@elainedizon , I am getting this: `Applozic/ALChatLauncher.h file not found` when I try to run the sample, do you happen to know of any solutions?

**Comment by reytum** [comment]
@murtraja This is related to this issue: https://github.com/AppLozic/Applozic-React-Native-Chat-Messaging-SDK/issues/9#issuecomment-470067529
